#!/bin/bash

test -z "$EDITOR" && EDITOR=sensible-editor
NUMBER=`ls issues | tail -1 | cut -d- -f1` 
FILE="issues/`expr $NUMBER + 1`-`echo "$@" | tr ' ' '-'`"
echo 'description: ' > "$FILE"
"$EDITOR" "$FILE" || rm "$FILE"
git add "$FILE"
