#!/bin/sh

while read localref localcommit remoteref remotecommit; do
	REFSPEC="${remotecommit}..${localcommit}"
	( git shortlog "$REFSPEC"; echo "review: $REFSPEC" ) \
		./scripts/new-issue "code review for $localref"
done

