#!/bin/bash

test -z "$*" && echo "Give issue summary on command line" && exit 1
test -z "$EDITOR" && EDITOR=sensible-editor
NUMBER=`ls issues | grep '^[0-9]\{4\}-' | tail -1 | cut -d- -f1` 
FILE="issues/`expr $NUMBER + 1`-`echo "$@" | tr ' ' '-'`"
echo 'description: ' > "$FILE"
"$EDITOR" "$FILE"
grep -qx 'description: ' "$FILE" && rm "$FILE" \
	&& echo "No description, deleting $FILE"
git add "$FILE"
